### ISSUE TITLE
LegalAidProviders Page Not Connecting - Error 404

### ISSUE THREAD

**Issue by rxhulshxrmx** [Jainprashuk/CodeLegalist#2]
When attempting to access the LegalAidProviders page, encounter a 404 error, indicating that the page is not found. This issue prevents access to the page and needs to be resolved.
<img width="918" alt="image" src="https://github.com/user-attachments/assets/723a9241-71cb-4dbe-9cd4-20dd8407e47c">

**Comment by Jainprashuk** [comment]
Issues Resolved
